"""Creating users table

Revision ID: 3e02364ebe70
Revises: 
Create Date: 2023-08-24 19:04:57.960205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3e02364ebe70"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            default="gen_random_uuid()",
            nullable=False,
        ),
        sa.Column(
            "permission",
            sa.Enum("ADMIN", "USER", name="userpermissionenum"),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    sa.Enum(name="userpermissionenum").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
