FROM python:alpine

RUN mkdir /app
WORKDIR /app

RUN \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

ADD ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

ADD ./flaskr  /app/flaskr
ENV FLASK_APP=flaskr/app.py

ADD ./tests /app/tests

RUN black --check .
RUN pytest -v --cov --cov-fail-under=100
RUN echo 'flask db upgrade -d flaskr/database/migrations && flask run --host=0.0.0.0 --debug' > /app/apply_migration_and_run.sh

CMD ["/bin/sh", "/app/apply_migration_and_run.sh" ]
